### PR TITLE
multiple fixes + cleanup + upgrade + replace search plugin

### PR DESCRIPTION
**Pull request by nick-genesis**
### What does this PR do?

- Adjusts the versions of all dependencies to the latest supported (reverts the previous downgrade).
- Replaces docusaurus-search-local with a forked version that supports docusaurus v3
- Removes unused dependencies and scripts / debloat
- Refactors config based on v3 default template
- Fixes cross-env part of local build and serve scripts
- Removes matomo (old analytics) and related patch-package logic
- Removes jsLoader override (esbuild-loader) // this was responsible for the react errors

### Search preview

image

### Local test steps:

```sh
git reset --hard && git clean --force -dfx && npm i && npm run build:base_url && npm run serve:base_url
```

### CODE REVIEW

**Review by MrBrunoWolff — COMMENTED** [review]
image

👀

**Comment by nick-genesis** [comment]
> image
> 
> 👀

You shouldn't have `@cmfcmf/docusaurus-search-local` anymore, using `@easyops-cn/docusaurus-search-local` now.
Did you nuke your `node_modules` and `package-lock.json`? (maybe just copy & paste the code snipper from the PR description)

**Comment by MrBrunoWolff** [comment]
> > image
> > 👀
> 
> You shouldn't have `@cmfcmf/docusaurus-search-local` anymore, using `@easyops-cn/docusaurus-search-local` now. Did you nuke your `node_modules` and `package-lock.json`? (maybe just copy & paste the code snipper from the PR description)

Thanks! Didn't really clean those things so it's **my fault**. Running again and it's already looking ok without those warnings.

**Review by MrBrunoWolff — APPROVED** [review]
Using the test steps here = ✅ works great

Build still warns about broken links but I believe this would be a "follow-up" PR.

Happy with the changes.

**Comment by nick-genesis** [comment]
@dbarros1979 can we get this merged in next before anything else please? I have re-synced it this morning.

**Comment by dbarros1979** [comment]
> @dbarros1979 can we get this merged in next before anything else please? I have re-synced it this morning.



> @dbarros1979 can we get this merged in next before anything else please? I have re-synced it this morning.

sure, let's do it. I got two issues last Friday, will Slack you to fix that and merge it. Thanks mate.

**Review by dbarros1979 — APPROVED** [review]

**Pull request merged**
