### PR TITLE
Handling empty and non-nullable fields in oracle

### PR DESCRIPTION
**Pull request by rafaelnferreira**
Thank you for contributing to the documentation.

Do the changes you have made apply to both Current and Previous versions?
No, this is only for future version.

Have you checked all new or changed links?
N/A

Is there anything else you would like us to know?
N/A

For reference: 

  - We have an [internal contributions guide](https://www.notion.so/genesisglobal/Contributing-new-documentation-75953fb245f246ff872789035451a0c4)
  - We have a [style guide](https://www.notion.so/genesisglobal/Documentation-style-guide-5b04ec6fe12f4262b90d192effd8059b) 

**This week's exciting excerpts from the style guide**

- We write in UK English, with Oxford English Dictionary (OED) spellings, grammar and vocabulary.  

Use the present tense wherever possible. Only use another tense where it is strictly necessary.

- Present tense (preferred whenever possible): *The script creates a new folder.*
- Future tense (avoid whenever possible): *The script will create a new folder.*

### CODE REVIEW

**Comment by wjhendry** [comment]
Hey @rafaelnferreira! Is this ready to be merged ow?

**Comment by rafaelnferreira** [comment]
@wjhendry ready now with 7.1 out. thanks

**Comment by wjhendry** [comment]
I'll open a new branch and add this text today. This will avoid the conflicts.

**Comment by wjhendry** [comment]
Information now addded on pull request https://github.com/genesiscommunitysuccess/docs/pull/1517

**Pull request closed without merging**
