### PR TITLE
Add in info box on expected date formats for SendIt

### PR DESCRIPTION
**Pull request by perryking**
Thank you for contributing to the documentation.

Do the changes you have made apply to both Current and Previous versions?
Yes 

Have you checked all new or changed links?
N/A - not changing links

Is there anything else you would like us to know?
No 

For reference: 

  - We have an [internal contributions guide](https://www.notion.so/genesisglobal/Contributing-new-documentation-75953fb245f246ff872789035451a0c4)
  - We have a [style guide](https://www.notion.so/genesisglobal/Documentation-style-guide-5b04ec6fe12f4262b90d192effd8059b) 

**This week's exciting excerpts from the style guide**

- We write in UK English, with Oxford English Dictionary (OED) spellings, grammar and vocabulary.  

Use the present tense wherever possible. Only use another tense where it is strictly necessary.

- Present tense (preferred whenever possible): *The script creates a new folder.*
- Future tense (avoid whenever possible): *The script will create a new folder.*

### CODE REVIEW

**Comment by perryking** [comment]
Before merging, just need to make sure the answer on this [ticket is](https://genesisglobal.atlassian.net/browse/PA-1229) inline with what i've added

**Review by wjhendry — APPROVED** [review]

**Comment by wjhendry** [comment]
Thanks. I'll merge tomorrow unless you shout!

**Comment by perryking** [comment]
i think this is fine, but as per [prev comment](https://github.com/genesiscommunitysuccess/docs/pull/1692#issuecomment-2137905577) just waiting for an update on PA ticket

**Comment by perryking** [comment]
i am good to merge now, @wjhendry! thank you!

**Review by wjhendry — APPROVED** [review]

**Pull request merged**
