### PR TITLE
docs: sync docs with FUI v 14.104.0 FUI-1580

### PR DESCRIPTION
**Pull request by matteematt**
Thank you for contributing to the documentation.

Do the changes you have made apply to both Current and Previous versions?

No

Have you checked all new or changed links?

Yes

Is there anything else you would like us to know?

No

For reference: 

  - We have an [internal contributions guide](https://www.notion.so/genesisglobal/Contributing-new-documentation-75953fb245f246ff872789035451a0c4)
  - We have a [style guide](https://www.notion.so/genesisglobal/Documentation-style-guide-5b04ec6fe12f4262b90d192effd8059b) 

**This week's exciting excerpts from the style guide**

- We write in UK English, with Oxford English Dictionary (OED) spellings, grammar and vocabulary.  

Use the present tense wherever possible. Only use another tense where it is strictly necessary.

- Present tense (preferred whenever possible): *The script creates a new folder.*
- Future tense (avoid whenever possible): *The script will create a new folder.*

### CODE REVIEW

**Comment by matteematt** [comment]
I can see the PR is failing due to a check for broken links, though when I run the app with `npm run start` the links in question seem to work correctly?

**Comment by nick-genesis** [comment]
> I can see the PR is failing due to a check for broken links, though when I run the app with `npm run start` the links in question seem to work correctly?

Hey mate, you likely need to run `npm run build` to see them (and sometimes with a BASE_URL too)
No worries, let me try it :)

**Comment by matteematt** [comment]
> > I can see the PR is failing due to a check for broken links, though when I run the app with `npm run start` the links in question seem to work correctly?
> 
> Hey mate, you likely need to run `npm run build` to see them (and sometimes with a BASE_URL too) No worries, let me try it :)

Thanks for the suggestion, though I just did `npm run build` and then `npm run start` and it still all seems to be working locally

**Comment by wjhendry** [comment]
When this happened to me, the links that caused the problems were in the Previous version - even though the error message didn't specify that

**Comment by matteematt** [comment]
@wjhendry I don't think I have changed the previous version though have I? I can see though if I view the change on githun though that the links are broken. 

Did you change the directory structure of the project recently? It seems to have added a `../` onto the front of the relative paths, but I can't think why

**Comment by nick-genesis** [comment]
Hi guys, I have confirmed it is due to building with a `BASE_URL` (`/docs/` in this case here).
Basically the number of `../` is wrong in some links because we're adding `/docs/` as a base.

These ones in particular
image

**Comment by wjhendry** [comment]
The structure has not changed. But I did have an identical problem linking to the package.json page a few weeks ago. 
The links work in the current and previous docs - and that was the case with my issue as well. And it worked with run start, like yours. Annoying, I know.

**Review by wjhendry — APPROVED** [review]

**Pull request merged**
