### PR TITLE
chore: bumping dependencies PTL-959

### PR DESCRIPTION
**Pull request by nick-genesis**
# Do not merge - testing

Your Jira ticket is:
PTL-959

Have you provided changes for all the relevant versions: next, 2022.4, 2023.1, etc?
N/A

Have you checked all new or changed links?
N/A

Is there anything else you would like us to know?

This PR update the following dependencies:
```
 @cmfcmf/docusaurus-search-local             ^0.11.0  →    ^1.1.0
 @docusaurus/core                             ^2.4.1  →    ^2.4.3
 @docusaurus/plugin-client-redirects          ^2.4.1  →    ^2.4.3
 @docusaurus/preset-classic                   ^2.4.1  →    ^2.4.3
 @docusaurus/theme-live-codeblock             ^2.4.1  →    ^2.4.3
 @emotion/react                             ^11.10.5  →  ^11.11.1
 @emotion/styled                            ^11.10.5  →  ^11.11.0
 @genesislcap/design-system-configurator     14.83.2  →   14.89.0
 @genesislcap/documentation-components       14.83.2  →   14.89.0
 @genesislcap/foundation-comms               14.83.2  →   14.89.0
 @genesislcap/foundation-entity-management   14.83.2  →   14.89.0
 @genesislcap/foundation-filters             14.83.2  →   14.89.0
 @genesislcap/foundation-header              14.83.2  →   14.89.0
 @genesislcap/foundation-layout              14.83.2  →   14.89.0
 @genesislcap/foundation-login               14.83.2  →   14.89.0
 @genesislcap/foundation-reporting           14.83.2  →   14.89.0
 @genesislcap/foundation-testing             14.83.2  →   14.89.0
 @genesislcap/foundation-zero                14.83.2  →   14.89.0
 @genesislcap/genx                           14.67.3  →   14.89.0
 @mui/icons-material                         ^5.11.0  →  ^5.14.13
 @mui/material                               ^5.11.6  →  ^5.14.13
 @types/mocha                                ^10.0.1  →   ^10.0.2
 dayjs                                        1.10.7  →   1.11.10
 dotenv                                      ^16.0.3  →   ^16.3.1
 esbuild                                     0.17.19  →    0.19.4
 esbuild-loader                               ^3.0.1  →    ^4.0.2
 fs-extra                                    ^11.1.0  →   ^11.1.1
 mdx-mermaid                                   1.3.2  →     2.0.0
 mermaid                                      ^9.3.0  →   ^10.5.0
 patch-package                                ^6.5.1  →    ^8.0.0
 react                                       ^17.0.0  →   ^17.0.2
 react-dom                                   ^17.0.0  →   ^17.0.2
 react-player                                ^2.11.0  →   ^2.13.0
 rimraf                                        5.0.1  →     5.0.5
 tslib                                        ^2.4.1  →    ^2.6.2
 webpack                                     ^5.83.1  →   ^5.88.2
 ```
 
 react and react-dom **not** updated for compatibility reasons
 ```
 Ignored incompatible updates (peer dependencies):
 react      ^17.0.0  →  ^18.2.0  reason: @docusaurus/core requires ^16.8.4 || ^17.0.0, @docusaurus/plugin-client-redirects requires ^16.8.4 || ^17.0.0, @docusaurus/preset-classic requires ^16.8.4 || ^17.0.0, @docusaurus/theme-live-codeblock requires ^16.8.4 || ^17.0.0, react-dom requires 17.0.2
 react-dom  ^17.0.0  →  ^18.2.0  reason: @docusaurus/core requires ^16.8.4 || ^17.0.0, @docusaurus/plugin-client-redirects requires ^16.8.4 || ^17.0.0, @docusaurus/preset-classic requires ^16.8.4 || ^17.0.0, @docusaurus/theme-live-codeblock requires ^16.8.4 || ^17.0.0
 ```
 
 config updated to use an async function for module exports so we can do this:
 `remarkPlugins: [(await import("mdx-mermaid")).default],`
 (newer version of mdx-mermaid not compatible with old require method)
 
 The rest of the changes in `docusaurus.config.ts` are from auto-formatting

### CODE REVIEW

**Comment by wjhendry** [comment]
Hello, @nick-genesis ! Is this something we need to get into the docs now?

**Comment by nick-genesis** [comment]
> Hello, @nick-genesis ! Is this something we need to get into the docs now?

Hello, this is likely outdated now, feel free to close it and I'll open a new one if needed, thanks.

**Comment by wjhendry** [comment]
> > Hello, @nick-genesis ! Is this something we need to get into the docs now?
> 
> Hello, this is likely outdated now, feel free to close it and I'll open a new one if needed, thanks.

Thanks. That is sensible.

**Comment by wjhendry** [comment]
Closed, as now out of date, but might be opened again later.

**Pull request closed without merging**
