### PR TITLE
chore: add missing @genesislcap/foundation-comms to the docs FUI-1255

### PR DESCRIPTION
**Pull request by derekdon**
Thank you for contributing to the documentation.

[FUI-1255](https://genesisglobal.atlassian.net/browse/FUI-1255): Update the docs project to include the package.

Screenshot 2023-05-23 at 17 12 24

Have you provided changes for all the relevant versions: next, 2022.4, 2023.1, etc?
Yes

Have you checked all new or changed links?
Yes

Is there anything else you would like us to know?
This is a long-overdue inclusion. It's been overlooked for some time and is arguably the most important foundation-ui package beyond the components themselves. It's a large changeset, but you can ignore all the `docs/api` contents. 

For reference: 

- if you are an internal contributor:
  - We have an [internal contributions guide](https://www.notion.so/genesisglobal/Contributing-new-documentation-75953fb245f246ff872789035451a0c4)
  - We have a [style guide](https://www.notion.so/genesisglobal/Documentation-style-guide-5b04ec6fe12f4262b90d192effd8059b) 
- If you are an external contributor:
  - We have an [external contribution guide](../Type-of-contribution)

**This week's exciting excerpt from the style guide**
LISTS. Only use numbered lists when the sequence is important. Usually, that is a set of instructions.
For example:
1. Change the dictionary files.
2. Run genesisInstall.
3. Run remap.
In all other cases, use an **unnumbered** list. OK?

### CODE REVIEW

**Review by MrBrunoWolff — COMMENTED** [review]
changes are ok!

Just not too sure about the actual link to the `foundation-comms`, see below:

docs-double-check

maybe make it `##` or have the link moved to a text inside the "API Docs" heading block.

Suggestion above is not a blocker for me.

**Comment by derekdon** [comment]
It should be the same as everywhere else, but I'll check in the morning. Thanks.

**Comment by MrBrunoWolff** [comment]
I meant the actual "look and feel" of the text as being a "heading+link" or not.

Right now, it's a different heading size and I not super sure about having it as a link too.

**1 - If we're making the heading a link:**

I'd suggest we do `## [API Docs](./docs/api/index.md)` for this (each case will be different but doesn't look right if the next item is larger).

Notice ## not ###, I believe this should match the next heading (License).

**2 - If we could avoid that**

I'd suggest not using "links" for these since they have the section/anchor link too. Why? You have the link to the heading which is a link itself?

Tricky scenario, which is why I'm happy with the item 1 above, but something like this could work too:

```
## API Docs

See the API Docs [here](./docs/api/index.md)
````

**Comment by derekdon** [comment]
I think foundation-header is currently the only outlier in the docs, based on what's been included so far.

Screenshot 2023-05-24 at 16 16 36

The idea of (3: smaller) ### rather than (2: larger) ## was I believe because we didn't want the API Docs link to carry the same visual weight as the actual README headings.

**Comment by wjhendry** [comment]
Are you talking about something like this?
image

**Comment by derekdon** [comment]
https://docusaurus.io/docs#fast-track same story. I think we're fine.

**Review by MrBrunoWolff — APPROVED** [review]

**Review by wjhendry — APPROVED** [review]

**Comment by wjhendry** [comment]
@derekdon Just checking - we are adding only to next and 23.1. I am very happy with that. Would you like me to merge?

**Review by nick-genesis — APPROVED** [review]
🚀

**Pull request merged**
