### PR TITLE
PTL-EXAMPLE-10-03-23: Added example changes for demo

### PR DESCRIPTION
**Pull request by IA-Walsh**
Thank you for contributing to the documentation.

Your Jira ticket is:
PTL-EXAMPLE

Have you provided changes for all the relevant versions: next, 2022.3, 2022.4, etc?

Have you checked all new or changed links?

Is there anything else you would like us to know?

For reference: 

- We have a [contributions guide](https://www.notion.so/genesisglobal/Contributing-new-documentation-75953fb245f246ff872789035451a0c4) 
- We have a [style guide](https://www.notion.so/genesisglobal/Documentation-style-guide-5b04ec6fe12f4262b90d192effd8059b) 

**This week's exciting excerpt from the style guide**
All our headings are in sentence case. For example:
- Really important information    **correct**
- Really Important Information    **not correct**

### CODE REVIEW

**Review by GuiWar — COMMENTED** [review]
I did not understand the changes. "Fake it till you make it"? do you have a ticket for that?

**Review by GuiWar — CHANGES_REQUESTED** [review]
Please, remove the phrases "Fake it till you make it".

**Comment by GuiWar** [comment]
Can we close this PR?

**Comment by wjhendry** [comment]
I have no idea why these lines are here.
Could you check with Ismail?
It doesn't look right to me




[cid:genesis-logo_61cae3c1-f120-4dce-aa4a-2cc1c66974cf.png]<https://genesis.global>

John Hendry | Senior Technical Writer
O: +44 (0) 20 3764 7514
1-3 Dufferin Street, London, EC1Y 8NA
genesis.global<https://genesis.global>
<https://genesis.global/genesis-global-wins-american-financial-technology-award/?utm_campaign=awards&utm_medium=email&utm_source=employee_email_sig>
Follow us:      [cid:social-bug-twitter_931c635f-ac1e-4586-a8a4-d9d0ed5c4050.png] <https://twitter.com/GenesisGlobalX>          [cid:social-bug-linkedin_1004256a-c1de-4c1f-8a45-802f794510af.png] <https://www.linkedin.com/company/genesis-global-technology/>


From: GuiWar ***@***.***>
Sent: 15 March 2023 11:58
To: genesiscommunitysuccess/docs ***@***.***>
Cc: John Hendry ***@***.***>; Review requested ***@***.***>
Subject: [Ext] Re: [genesiscommunitysuccess/docs] PTL-EXAMPLE-10-03-23: Added example changes for demo (PR #1026)

External email. Use caution when clicking links or opening file attachments.


Can we close this PR?

-

**Pull request closed without merging**
